apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykudos-api
  labels:
    app: mykudos-api
    name: mykudos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mykudos-api
  template:
    metadata:
      labels:
        app: mykudos-api
    spec:
      containers:
        - name: mykudos-api
          image: docker.lps.krthomolog.com.br/mykudos-api:[VERSION_CI]
          env:
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: mykudos-api-config
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: mykudos-api-config
                  key: KEYCLOAK_CLIENT
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: mykudos-api-config
                  key: KEYCLOAK_REALM
            - name: MONITOR_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: mykudos-api-config
                  key: MONITOR_APP_NAME
            - name: MONITOR_URL
              valueFrom:
                configMapKeyRef:
                  name: mykudos-api-config
                  key: MONITOR_URL
            - name: MONITOR_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mykudos-api-config
                  key: MONITOR_BASE_URL
            - name: LOGGER_URL
              valueFrom:
                configMapKeyRef:
                  name: mykudos-api-config
                  key: LOGGER_URL
            - name: LOGGER_PORT
              valueFrom:
                configMapKeyRef:
                  name: mykudos-api-config
                  key: LOGGER_PORT
            - name: LOGGER_ENV
              valueFrom:
                configMapKeyRef:
                  name: mykudos-api-config
                  key: LOGGER_ENV
            - name: LOGGER_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: mykudos-api-config
                  key: LOGGER_LEVEL
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
